### ISSUE TITLE
Copy and Generate Button Not Working

### ISSUE THREAD

**Issue by AmreshSinha** [surajshende247/Password-Knitter#5]
**Describe the bug**
On Clicking Copy nothing is being copied to my clipboard. Generate is not working too.

**To Reproduce**
1. Go to Site
2. Click on Copy and Generate Button

**Expected behavior**
On Pressing Copy it should have added the password to my clipboard.
The same is with the Generate. It's not generating new password.

**Screenshots**
![image](https://user-images.githubusercontent.com/35039730/135428016-4b548390-a7ea-456c-a9c2-8854de919c5f.png)

**Desktop (please complete the following information):**
 - OS: Manjaro OS
 - Browser: Chrome

**Smartphone (please complete the following information):**
Not Tested on Mobile Device

**Comment by AmreshSinha** [comment]
Can I work on this issue?

**Comment by surajshende247** [comment]
@AmreshSinha Yes, you can start working on this issue

**Comment by AmreshSinha** [comment]
Created a PR https://github.com/surajshende247/Password-Knitter/pull/6

**Comment by MarufSharifi** [comment]
could i work on this?

**Comment by surajshende247** [comment]
> could i work on this?

@MarufSharifi Yes.  you can start working on this issue

**Comment by AmreshSinha** [comment]
https://github.com/surajshende247/Password-Knitter/pull/7
Created a PR

**Comment by AmreshSinha** [comment]
thanks for merging @surajshende247 
but the label should be
"hacktoberfest-accepted" :blush:
